# Generated by Django 3.2.4 on 2021-06-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=60)),
                ('home_town', models.CharField(max_length=110)),
                ('board_sponsor', models.CharField(max_length=130)),
                ('shoe_sponsor', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tricks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trick_name', models.CharField(max_length=100)),
                ('signature_trick', models.CharField(max_length=100)),
                ('favorite_trick', models.CharField(max_length=120)),
                ('trick_location', models.CharField(max_length=150)),
                ('photo_url', models.TextField()),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='skater_api.skater')),
            ],
        ),
    ]
